apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrt
  template:
    metadata:
      labels:
        app: dhnmrt
    spec:
      containers:
      - image: okteto.dev/dhnmrt:latest
        name: dhnmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "49608c90-698d-4bfa-a7d5-051aacba8614"
        - name: Vless_Path
          value: "/vl2etv5"
        - name: Vmess_UUID
          value: "49608c90-698d-4bfa-a7d5-051aacba8614"
        - name: Vmess_Path
          value: "/vm486"
        - name: Share_Path
          value: "/v2link"
